LCFS-1280: Validation for Quantity Supplied in Fuel Supply.
bcgov/lcfs pull request #1335
Opened 2024-12-02 20:13 UTC by areyeslo

- The default **Quantity supplied** value being 0 should not be allow. 
- Zero should not be a valid amount in a fuel supply record and the row should not save until the user has entered a value.

[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=88333582&issue=bcgov%7Clcfs%7C1280)

2024-12-02 22:08 UTC, AlexZorkin requested changes
Looks good, I would just like to see a frontend test covering this 0 quantity state and that it shows the error correctly.

2024-12-06 17:56 UTC, AlexZorkin commented
Let's get this merged, just need to fix the conflicts, otherwise looks good to go.

2024-12-11 20:34 UTC, AlexZorkin requested changes
We don't want to add this validation across quantity fields, i think just focus on fuel_supply. If you hear differently from business area then let me know.

2024-12-11 21:10 UTC, areyeslo commented on backend/lcfs/web/api/notional_transfer/schema.py
> +    quantity: int = Field(
Let me check with Lindy and update the ticket if applicable.

2024-12-13 21:20 UTC, areyeslo commented on backend/lcfs/web/api/transaction/schema.py
> +    quantity: int = Field(
Removed this validation

2024-12-13 21:20 UTC, areyeslo commented on backend/lcfs/web/api/notional_transfer/schema.py
> +    quantity: int = Field(
Removed this validation

2024-12-17 17:54 UTC, AlexZorkin approved these changes

2024-12-17 19:29 UTC, merged