Feat: Enforce mandatory fuel code validation for schedules - 1429
bcgov/lcfs pull request #1461
Opened 2024-12-13 20:50 UTC by hamed-valiollahi

This PR implements logic to enforce mandatory fuel code selection in schedules when "Fuel code - section 19 (b) (i)" is chosen.

Closes #1429

2024-12-13 22:46 UTC, areyeslo commented on backend/lcfs/web/application.py
> +import debugpy
Do we need these new imports?

2024-12-13 22:47 UTC, areyeslo requested changes
Looks great! Tested and works great!. Just wondering if we need those imports?

2024-12-16 16:46 UTC, hamed-valiollahi commented
> Looks great! Tested and works great!. Just wondering if we need those imports?

Thanks for the code review. We need these imports for backend debugging purposes. It looks like they were accidentally removed. They enable remote debugging in development if needed. Please refer to line 111 of this file for more details.

2024-12-17 16:39 UTC, areyeslo approved these changes
LGTM

2024-12-17 17:10 UTC, merged