Feat: org transfer flag 222
bcgov/lcfs pull request #364
Opened 2024-02-05 18:03 UTC by kevin-hashimoto

- feat: added operating_name to org model
- feat: added operating_name value to seeders
- feat: updated update org service/repo
- refactor: renamed `AddOrganization` to `AddEditOrg`
- feat: added component flag `mode` to `AddEditOrg` so it can use the right endpoints depending on adding or updating org

TODO:
- frontend: conditional filter to hide/display organizations in the list for bceid users when looking at the transfer partners list

notes:
- `AddEditOrg` should probably be cleaned up down the road, it is getting quite big and there are some pieces that can be simplified

2024-02-13 23:18 UTC, AlexZorkin requested changes

2024-02-13 23:18 UTC, AlexZorkin commented on frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
What are your thoughts on just checking whether orgID exists to determine "mode" rather than explicitly settings it in the route?

2024-02-13 23:18 UTC, AlexZorkin commented on frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
We definitely need to break this component up. Please write up a few ways we could separate out its parts. I'll use this in a followup ticket.

2024-02-13 23:18 UTC, AlexZorkin commented on frontend/src/views/Transactions/Transactions.jsx
> +        {currentUserOrgData?.org_status.status === 'Registered' && (
Let's add 'Registered' as a constant for the app

2024-02-14 00:44 UTC, kevin-hashimoto commented on frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
I was thinking of that originally. that way we can combine create and update db functions too ( it would essentially become an upsert function ). One thing I like about having a flag is if there are any client side differences from updating vs create views ( so far there isnt, may be a future consideration? ).

Ill change it to check on the backend and adjust the update/create functions to become a upsert function. #160 also touches the create function so It will be fixed with this update as well.

2024-02-14 01:48 UTC, kevin-hashimoto commented on frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
Instead of mode, we can check if the path param `orgID` is present to determine to create or update.
With this we can still separate the http methods POST for creating and PUT for updating _with_ path params

2024-02-14 02:08 UTC, kevin-hashimoto commented on frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
added to original comment

2024-02-15 18:01 UTC, AlexZorkin approved these changes

2024-02-15 18:01 UTC, merged