Feat: delete draft transfer #228
bcgov/lcfs pull request #420
Opened 2024-02-24 02:28 UTC by kevin-hashimoto

#228 

- refactor: overhaul of the `AddEditTransfer` component and its child components
- feat: confirmation modal
- feat: button cluster configuration and display
- feat: new endpoints

TODO:
- Transaction page grid display
  - Create the endpoint for paginated transactions
  - Alter the grid component on the Transactions page to display the paginated transaction data
- Transaction page alert display
  - detect alerts when a user lands on the Transactions page.
  
  
  Notes:
- The new patterns in the `AddEditTransfer` component should set us up to easily integrate the rest of the transfers features. This should be merged in before starting other components of the transfers.
- Different states of the child component UIs should be determined by checking the status of the transfer. `transferData?.transfer_status.status`

2024-02-27 23:50 UTC, AlexZorkin requested changes
Looks great. You'll have to merge release into this branch first because there are a few breaking changes that need to be fixed around transfer_status getting renamed to current_status. Mentioned in comments.

2024-02-27 23:50 UTC, AlexZorkin commented on backend/lcfs/web/api/transfer/services.py
> +        transfer.transfer_status_id = transfer_data.transfer_status_id
this value has recently been updated to current_status_id so we'll need to swap that out here. Reason being is the TransferHistory table will keep the change history for each transfer, ie when their status changes. Please add the creation of a new TransferHistory record here with the new status, and set current_status on the Transfer record.

2024-02-27 23:50 UTC, AlexZorkin commented on backend/lcfs/web/api/transfer/services.py
Please make sure the backend unit tests are working with these changes, and add any additional coverage needed for the update_transfer method.

2024-02-27 23:50 UTC, AlexZorkin commented on backend/lcfs/web/api/transfer/views.py
add/update the backend unit tests for update_transfer_draft

2024-02-28 01:36 UTC, kevin-hashimoto commented
@AlexZorkin fixes addressed

2024-02-28 17:43 UTC, merged