Feat/prashanth fuel code save 432
bcgov/lcfs pull request #587
Opened 2024-04-29 22:52 UTC by prv-proton

- Backend Fuel Code tables
- APIs to get list of fuel codes and to add new fuel codes - extension of #431 
- UI to display fuel codes
- UI to edit and add fuel codes using ag-grid.

2024-04-30 21:42 UTC, AlexZorkin requested changes
Overall looks good. The table interactions need some cleanup which is outlined below:

* Validation shouldn’t run on an empty row, only after making a first selection should the error validation show.
* When clicking into a text input field, the selection border color should be blue rather than red. The red border makes it look like there’s an error.
* The read only fields show a ‘click hand’ when hovering over them which is confusing.
* When hovering over read only field, all read only fields are getting highlighted. Read only fields should not be highlighted or interactable. 
* Read only fields are currently selectable with a red border, they should not be selectable.
* Last updated read only empty field should have a placeholder. N/A?
* Red border highlighting is hard to see around field with validation issue. Need to increase cell margin or padding to make it move visible.
* In multiselect option cell, when multiple pills overflow first row, the x clear button is shifting out of position, it should stay fixed in its cell right center position.
* On ‘Save draft code’ button click, any error validation should show above the table on each click. Currently it is only showing on load.
* When multiple empty rows are in the table, the select default and date default placeholders should be visible, currently they are hiding until the row is clicked.
* Each new row is currently defaulting with “Fuel production facility location is required” error. New empty rows should not start with validation errors.
* After saving a fuel code, in the fuel code table, the new record doesn't show any data and instead is showing blank input fields. This should show read only fields with the fuel code data.

2024-04-30 23:07 UTC, prv-proton commented
> * Validation shouldn’t run on an empty row, only after making a first selection should the error validation show.
> * When clicking into a text input field, the selection border color should be blue rather than red. The red border makes it look like there’s an error.
> * The read only fields show a ‘click hand’ when hovering over them which is confusing.
> * When hovering over read only field, all read only fields are getting highlighted. Read only fields should not be highlighted or interactable.
> * Read only fields are currently selectable with a red border, they should not be selectable.
> * Last updated read only empty field should have a placeholder. N/A?
> * Red border highlighting is hard to see around field with validation issue. Need to increase cell margin or padding to make it move visible.
> * In multiselect option cell, when multiple pills overflow first row, the x clear button is shifting out of position, it should stay fixed in its cell right center position.
> * On ‘Save draft code’ button click, any error validation should show above the table on each click. Currently it is only showing on load.
> * When multiple empty rows are in the table, the select default and date default placeholders should be visible, currently they are hiding until the row is clicked.
> * Each new row is currently defaulting with “Fuel production facility location is required” error. New empty rows should not start with validation errors.
> * After saving a fuel code, in the fuel code table, the new record doesn't show any data and instead is showing blank input fields. This should show read only fields with the fuel code data.

- [ ] Validation shouldn’t run on an empty row, only after making a first selection should the error validation show.
- [ ] When clicking into a text input field, the selection border color should be blue rather than red. The red border makes it look like there’s an error.
- [ ] The read only fields show a ‘click hand’ when hovering over them which is confusing.
- [ ] When hovering over read only field, all read only fields are getting highlighted. Read only fields should not be highlighted or interactable.
- [ ] Read only fields are currently selectable with a red border, they should not be selectable.
- [ ] Last updated read only empty field should have a placeholder. N/A?
- [ ] Red border highlighting is hard to see around field with validation issue. Need to increase cell margin or padding to make it move visible.
- [ ] In multiselect option cell, when multiple pills overflow first row, the x clear button is shifting out of position, it should stay fixed in its cell right center position.
- [ ] On ‘Save draft code’ button click, any error validation should show above the table on each click. Currently it is only showing on load.
- [ ] When multiple empty rows are in the table, the select default and date default placeholders should be visible, currently they are hiding until the row is clicked.
- [ ] Each new row is currently defaulting with “Fuel production facility location is required” error. New empty rows should not start with validation errors.
- [ ] After saving a fuel code, in the fuel code table, the new record doesn't show any data and instead is showing blank input fields. This should show read only fields with the fuel code data.

2024-05-02 13:51 UTC, prv-proton commented
> Overall looks good. The table interactions need some cleanup which is outlined below:
> 
> * Validation shouldn’t run on an empty row, only after making a first selection should the error validation show.
> * When clicking into a text input field, the selection border color should be blue rather than red. The red border makes it look like there’s an error.
> * The read only fields show a ‘click hand’ when hovering over them which is confusing.
> * When hovering over read only field, all read only fields are getting highlighted. Read only fields should not be highlighted or interactable.
> * Read only fields are currently selectable with a red border, they should not be selectable.
> * Last updated read only empty field should have a placeholder. N/A?
> * Red border highlighting is hard to see around field with validation issue. Need to increase cell margin or padding to make it move visible.
> * In multiselect option cell, when multiple pills overflow first row, the x clear button is shifting out of position, it should stay fixed in its cell right center position.
> * On ‘Save draft code’ button click, any error validation should show above the table on each click. Currently it is only showing on load.
> * When multiple empty rows are in the table, the select default and date default placeholders should be visible, currently they are hiding until the row is clicked.
> * Each new row is currently defaulting with “Fuel production facility location is required” error. New empty rows should not start with validation errors.
> * After saving a fuel code, in the fuel code table, the new record doesn't show any data and instead is showing blank input fields. This should show read only fields with the fuel code data.

Thanks for the comments, all the comments have been addressed. Please review and let me know if still any issues.

2024-05-03 16:25 UTC, AlexZorkin approved these changes

2024-05-03 16:25 UTC, merged