Feat: Display Fuel Supply in Report Details Section - 717
bcgov/lcfs pull request #787
Opened 2024-07-29 19:35 UTC by hamed-valiollahi

This PR adds the Fuel supply display table to the 'Report details' section. A few table column values need to be determined.

### Improvements
- Add Docker Compose container and volume names to avoid creating numerous node module volumes over time and to optimize storage usage.

Closes #717

2024-07-30 17:15 UTC, AlexZorkin requested changes
Looks good. Just two minor comments. ty

2024-07-31 17:49 UTC, hamed-valiollahi commented on backend/lcfs/web/api/fuel_supply/schema.py
> +    # unit: str
Of course, I removed all these unneeded commanded lines.

2024-07-31 23:02 UTC, AlexZorkin commented on docker-compose.yml
Yes thats great thank you! remove all those unnecessary volumes.

2024-08-01 16:06 UTC, hamed-valiollahi commented on docker-compose.yml
Sure, thank you for your feedback, Alex!

2024-08-06 16:49 UTC, prv-proton commented
closing as already merged with editor ticket

2024-08-06 16:49 UTC, closed without merging