Refactor: Rename Fuel Class to Fuel Instance and Add Unrecognized Field - 850
bcgov/lcfs pull request #890
Opened 2024-09-09 15:42 UTC by hamed-valiollahi

This PR refactors the Fuel Class table to Fuel Instance and adds an unrecognized field to fuel types.

Closes #850

2024-09-09 20:26 UTC, AlexZorkin requested changes
Looks good, just a few logic pieces we need to keep in place.

2024-09-09 20:26 UTC, AlexZorkin commented on frontend/src/views/AllocationAgreements/_schema.jsx
> -    editable: (params) => params.data.fuelType === 'Other',
We have to leave this: params.data.fuelType === 'Other' 
Reason is that we need to allow input of new custom fuel_types if Other is selected.

2024-09-09 20:26 UTC, AlexZorkin commented on frontend/src/views/FuelSupplies/_schema.jsx
> -      const conditionalStyle = /other/i.test(params.data.fuelType)
again need to leave the existing logic in place.

2024-09-11 16:29 UTC, hamed-valiollahi commented
> Looks good, just a few logic pieces we need to keep in place.

Thanks, Alex, for your feedback! I’ve made the changes.

2024-09-12 22:19 UTC, AlexZorkin approved these changes

2024-09-12 22:19 UTC, merged